log:
  level: debug
  format: text

prometheus:
  path: /metrics
  port: 8080

openapi:
  url: https://petstore3.swagger.io/api/v3/openapi.json
  # file: ./testdata/spec.yaml
  reload: 6h

# metrics:
#   headers:
#     - user-agent
